### ISSUE TITLE
Env error

### ISSUE THREAD

**Issue by adamjsturge** [adamjsturge/xsshunter-go#135]
```
Error on parse multiform request Content-Type isn't multipart/form-data
fatal error: concurrent map writes

goroutine 1655 [running]:
main.get_env(...)
        /app/util.go:48
main.get_host(0xc0000ea000)
        /app/const.go:28 +0x7b
main.probeHandler({0xac99e0, 0xc00029c000}, 0xc0000ea000)
        /app/main.go:314 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc000194178?, {0xac99e0?, 0xc00029c000?}, 0x72ef76?)
        /usr/local/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x46b139?, {0xac99e0, 0xc00029c000}, 0xc0000ea000)
        /usr/local/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc0001ec0f0?}, {0xac99e0?, 0xc00029c000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0001f0090, {0xacaac8, 0xc0002b0b10})
        /usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 1 [runnable]:
internal/poll.(*FD).Accept(0xc000198600)
        /usr/local/go/src/internal/poll/fd_unix.go:613 +0x364
net.(*netFD).accept(0xc000198600)
        /usr/local/go/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc0000c6800)
        /usr/local/go/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc0000c6800)
        /usr/local/go/src/net/tcpsock.go:372 +0x30
net/http.(*Server).Serve(0xc0002be000, {0xac9cb0, 0xc0000c6800})
        /usr/local/go/src/net/http/server.go:3330 +0x30c
net/http.(*Server).ListenAndServe(0xc0002be000)
        /usr/local/go/src/net/http/server.go:3259 +0x71
main.main()
        /app/main.go:80 +0x78c

goroutine 7 [select, 2116 minutes]:
database/sql.(*DB).connectionOpener(0xc0000e8b60, {0xacab00, 0xc00019c1e0})
        /usr/local/go/src/database/sql/sql.go:1253 +0x87
created by database/sql.OpenDB in goroutine 1
        /usr/local/go/src/database/sql/sql.go:833 +0x130

goroutine 1656 [IO wait]:
internal/poll.runtime_pollWait(0x1490c3ff2d70, 0x72)
        /usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc0001c4080?, 0xc0001ec101?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001c4080, {0xc0001ec101, 0x1, 0x1})
        /usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc0001c4080, {0xc0001ec101?, 0xc0004c4748?, 0x472c10?})
        /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0001ee008, {0xc0001ec101?, 0x0?, 0xc0002b0098?})
        /usr/local/go/src/net/net.go:189 +0x45
net/http.(*connReader).backgroundRead(0xc0001ec0f0)
        /usr/local/go/src/net/http/server.go:690 +0x37
created by net/http.(*connReader).startBackgroundRead in goroutine 1655
        /usr/local/go/src/net/http/server.go:686 +0xb6

goroutine 1654 [runnable]:
unicode.SimpleFold(0x52?)
        /usr/local/go/src/unicode/letter.go:340 +0xef
regexp/syntax.(*compiler).rune(0xc0000a88a0, {0xc0000907dc, 0x1, 0x9}, 0xd4)
        /usr/local/go/src/regexp/syntax/compile.go:278 +0x1e5
regexp/syntax.(*compiler).compile(0xc0000a88a0, 0xc00019a620)
        /usr/local/go/src/regexp/syntax/compile.go:101 +0x157f
regexp/syntax.Compile(0xc00019a620)
        /usr/local/go/src/regexp/syntax/compile.go:74 +0x135
regexp.compile({0xa05c8c, 0xc}, 0xe250?, 0x0)
        /usr/local/go/src/regexp/regexp.go:176 +0x77
regexp.Compile(...)
        /usr/local/go/src/regexp/regexp.go:131
regexp.MustCompile({0xa05c8c, 0xc})
        /usr/local/go/src/regexp/regexp.go:311 +0x2c
main.probeHandler({0xac99e0, 0xc0001942a0}, 0xc00017a780)
        /app/main.go:316 +0x17b
net/http.HandlerFunc.ServeHTTP(0xc000194178?, {0xac99e0?, 0xc0001942a0?}, 0x72ef76?)
        /usr/local/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x46b139?, {0xac99e0, 0xc0001942a0}, 0xc00017a780)
        /usr/local/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc0000db890?}, {0xac99e0?, 0xc0001942a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc0001f0000, {0xacaac8, 0xc0002b0b10})
        /usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3360 +0x485

goroutine 1055 [IO wait]:
internal/poll.runtime_pollWait(0x1490c3ff30b8, 0x72)
        /usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc0001c4000?, 0xc0000db8a1?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001c4000, {0xc0000db8a1, 0x1, 0x1})
        /usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc0001c4000, {0xc0000db8a1?, 0x732c723d69206573?, 0x2c6528663b30213d?})
        /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc0001ee000, {0xc0000db8a1?, 0x6c206e6f6974636e?, 0x722c6e2c652c7428?})
        /usr/local/go/src/net/net.go:189 +0x45
net/http.(*connReader).backgroundRead(0xc0000db890)
        /usr/local/go/src/net/http/server.go:690 +0x37
created by net/http.(*connReader).startBackgroundRead in goroutine 1654
        /usr/local/go/src/net/http/server.go:686 +0xb6
```

**Comment by adamjsturge** [comment]
Fixed
